# -*- coding: utf-8 -*-
"""imagedatagen on faces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FsNsaZ91eyDC9n0VYTDcOLkSINZXyGmo
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils
import os

import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt
import os
#from PIL import Image
from numpy import*
import scipy.ndimage
from scipy import ndimage
import os
import cv2
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

datagen = ImageDataGenerator(width_shift_range=0.1,
                             height_shift_range=0.1,
                             shear_range=0.15,
                             zoom_range = 0.1,
                             channel_shift_range = 10, 
                             featurewise_center = True,
                             featurewise_std_normalization=True)

datagen = ImageDataGenerator(featurewise_std_normalization=True)

import tensorflow
from IPython.display import display
from PIL import Image
#from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder

import keras
path1 =r'/content/gdrive/My Drive/face_i_to_a'
save_here =r'/content/gdrive/My Drive/faces/train/a'
listing=os.listdir(path1)
num_samples=size(listing)
print (num_samples)   

for file in listing:
    image= Image.open(path1 + '/' + file)
    image = np.expand_dims(image, 0)
   # image = image[..., None]
    datagen.fit(image)
    for x, val in zip(datagen.flow(image, save_to_dir=save_here, save_prefix='aug', save_format='jpg'),range(3)):
        pass