# -*- coding: utf-8 -*-
"""predicting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BhV5xL580gsA1Z3sobX_ZcRnL6-Jz_jF
"""

from google.colab import drive
drive.mount('/content/gdrive')

import cv2
import os
import numpy as np

# load and evaluate a saved model
from numpy import loadtxt
from keras.models import load_model
 
# load model
model1 = load_model('/content/gdrive/My Drive/model/f.h5')

IMG_SIZE=150
img_rows,img_cols=150,150
path='/content/gdrive/My Drive/see/a.jpeg'

img_array1 = cv2.imread(os.path.join(path))
new_array1 = cv2.resize(img_array1, (IMG_SIZE, IMG_SIZE))

X = np.array(new_array1).reshape(-1, IMG_SIZE, IMG_SIZE, 3)

Y = model1.predict(X)
print(Y)